// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICprD7Zx21ClFu5ys71tAP89QocXbFDI',
    appId: '1:461962602120:android:862b91c21d4a8e090d613d',
    messagingSenderId: '461962602120',
    projectId: 'naturemedix-32764',
    storageBucket: 'naturemedix-32764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6xevyCr5QymvFkhaHlLKhZiY_HtkloM',
    appId: '1:461962602120:ios:7229478172739d2e0d613d',
    messagingSenderId: '461962602120',
    projectId: 'naturemedix-32764',
    storageBucket: 'naturemedix-32764.firebasestorage.app',
    androidClientId:
        '461962602120-dhvb4oqebdpvfjji72t9glubj1ieso2v.apps.googleusercontent.com',
    iosClientId:
        '461962602120-q8iqr7vala8n8v4821iassu3gc9r4mnv.apps.googleusercontent.com',
    iosBundleId: 'com.difrancescogianmarco.arcoreFlutterPluginExample',
  );
}
